id: ebc2548c-a4c3-402a-b617-389da41292d7
name: mysql-sdk-plugin
language: PYTHON27
hostTypes:
- UNIX
pluginType: STAGED
entryPoint: plugin_runner:plugin
srcDir: src
schemaFile: schema.json
buildNumber: 2.0.31
